### ISSUE TITLE
C++ makfile 

### ISSUE THREAD

**Issue by Yixiangzhang1996** [brunonevado/MutationAccumulation#1]

**Comment by brunonevado** [comment]
Hi,

Thanks, and sorry this is not working for you.

I have no experience installing bio++ into non-default locations, but I think somewhere inside the installation folder you defined with DCMAKE_INSTALL_PREFIX="the library folder" you should now have two folders: one called "include" and the other "lib" or "libbpp". In the makefile, "IDIR" should point to the "include" folder, and "LDIR" to the "lib" or "libbpp" folder.

Let me know if that helps,
Bruno

**Comment by Yixiangzhang1996** [comment]
Hello  Bruno:
Thank for your reply.It helps.Well,I didn't work out this problem. Now I search the error information on the Google. It seems that the .all files are deprecated since some time.  Maybe I could change the grammar in the  main.cpp.,helpping it works.
Thanks again.
Andrew
